In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from ydata_profiling import ProfileReport
import numpy as np

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.dtypes

Unnamed: 0      int64
TV            float64
Radio         float64
Newspaper     float64
Sales         float64
dtype: object

In [6]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [9]:
df.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [10]:
pf = ProfileReport(df)

In [11]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
pf.to_file('test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
x = df[['TV']]
y = df[['Sales']]

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
linear = LinearRegression()

In [18]:
linear.fit(x,y)

LinearRegression()

In [19]:
linear.intercept_

array([7.03259355])

In [20]:
linear.coef_

array([[0.04753664]])

In [22]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file, 'wb'))

In [24]:
linear.predict([[45]])

array([[9.17174237]])

In [28]:
saved_model = pickle.load(open(file, 'rb'))

In [29]:
saved_model.predict([[45]])

array([[9.17174237]])

In [30]:
pickle.dump(linear, open('model.pkl', 'wb'))

In [32]:
pickled_model = pickle.load(open('model.pkl', 'rb'))

In [33]:
pickled_model.predict([[45]])

array([[9.17174237]])

In [92]:
pickled_model.score(x,y)

0.611875050850071

In [34]:
linear.score(x,y)

0.611875050850071

In [62]:
data={
"TV" : 230.1
}

In [63]:
data.keys()

dict_keys(['TV'])

In [64]:
data.values()

dict_values([230.1])

In [65]:
list(data.values())

[230.1]

In [84]:
output1 = pickled_model.predict([[230.1]])

In [85]:
output1

array([[17.97077451]])

In [72]:
 pickled_model.predict([[230.1]])[0]

array([17.97077451])

In [91]:
 pickled_model.predict([[230.1]])[0][0]

17.97077451276554

In [89]:
list( pickled_model.predict([[230.1]]))[0][0]

17.97077451276554